[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "langchain-groq>=0.3.5",
    "langchain-mcp-adapters>=0.1.9",
    "langgraph>=0.5.2",
    "mcp[cli]>=1.11.0",
]
